fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0  # this is optional, use `pre-commit autoupdate` to get the latest rev!
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: forbid-submodules
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: bump-my-version
        name: bump-my-version
        entry: bump-my-version
        args: ["replace", "--allow-dirty"]
        pass_filenames: false
        language: system

  - repo: https://github.com/psf/black
    rev: 26.1.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/isort
    rev: 8.0.1
    hooks:
      - id: isort

  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle

  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
      - id: mypy
        additional_dependencies: &TESTDEPS
          - "GitPython>=3"
          - "matplotlib"
          - "matplotlib-stubs"
          - "pandas"
          - "pandas-stubs"
          - "pydantic"
          - "pylint-pydantic"
          - "pytest"
          - "python-dateutil"
          - "numpy <2.5"
          - "rich_click"
          - "ruamel.yaml"
          - "seaborn"
          - "semver"
          - "tol_colors"
          - "types-python-dateutil"
          - "types-requests"
          - "types-seaborn"
        args: ["--python-version=3.11", "--explicit-package-bases"]

  - repo: https://github.com/PyCQA/pylint
    rev: v4.0.5
    hooks:
      - id: pylint
        additional_dependencies: *TESTDEPS
