# PyCodeStyle
# config see https://pycodestyle.pycqa.org/en/latest/intro.html
#
# Seemingly no pyproject.toml yet, thus config is here.
[pycodestyle]
count = False
#ignore = E226,E302,E41
exclude = .git/, .snakemake/, .pytest_cache/, sync-test-env/, conda/, env/
max-line-length = 120
statistics = True
