#!/usr/bin/env bash
# usage: ./extract_all.sh jemalloc_data_sets.list

listfile="$1"

while IFS= read -r archive; do
    # skip empty lines
    [ -z "$archive" ] && continue

    base="${archive%.tgz}"   # strip .tgz -> x
    mkdir -p "$base"
    tar -xzf "$archive" -C "$base"
done < "$listfile"
