source:
  host: hambach
  path: /projects/bennch-data/bennch-datadump/
vars:
  PIPELINE_ID:
    path: 0*_bench/work/metadata/env-vars.out
    parser: grep -i PIPELINE_ID
  GATHER_METADATA_VERS:
    path: 0*_bench/work/metadata/gather.json
    parser: jq .version
  creation-time:
    path: 0*_bench/work/data/logfile_0
    parser: grep -i py_time_connect
  threads_per_task:
    path: 0*_bench/work/data/logfile_0
    parser: grep "^local_num_threads " | cut -f2 -d" "
  time_simulate:
    path: 0*_bench/work/data/logfile_0
    parser: grep "^time_simulate_cpu " | cut -f2 -d" "

current_set:
  setid: 9c9dee4a7cb395bea685aa2edbe0887c
