parameter_labels:
  threads_per_node: OMP threads
  tasks_per_node: MPI processes
  num_nodes: Nodes
  wall_time_total: Total
  wall_time_preparation: Preparation
  wall_time_presim: Presimulation
  wall_time_creation: Creation
  wall_time_connect: Connection
  time_simulate: State propagation
  wall_time_phase_total: All phases
  time_update_spike_data: Update
  wall_time_phase_collocate: Collocation
  time_communicate_spike_data: Communication
  time_deliver_spike_data: Delivery
  time_construction_create+time_construction_connect: Network construction
  time_construction_create: Time create
  time_construction_connect: Time connect
  max_memory: Memory
  sim_factor: State propagation
  frac_phase_update: Update
  frac_phase_communicate: Communication
  frac_phase_deliver: Delivery
  frac_phase_collocate: Collocation
  phase_update_factor: Update
  phase_communicate_factor: Communication
  phase_deliver_factor: Delivery
  phase_collocate_factor: Collocation
  phase_total_factor: All phases
  total_memory: Memory
  total_memory_per_node: Memory per node

data_definition:
  num_nodes: first
  threads_per_task: first
  tasks_per_node: first
  model_time_sim: first
  time_construction_create: [mean, std]
  time_construction_connect: [mean, std]
  time_simulate: [mean, std]
  time_collocate_spike_data: [mean, std]
  time_communicate_spike_data: [mean, std]
  time_deliver_spike_data: [mean, std]
  # 'time_update': ['mean', 'std']
  time_communicate_target_data: [mean, std]
  time_gather_spike_data: [mean, std]
  time_gather_target_data: [mean, std]
  time_communicate_prepare: [mean, std]
  py_time_create: [mean, std]
  py_time_connect: [mean, std]
  base_memory: [mean, std]
  network_memory: [mean, std]
  init_memory: [mean, std]
  total_memory: [mean, std]
  num_connections: [mean, std]
  local_spike_counter: [mean, std]
