#!/usr/bin/env bash


# slide 8: original finding, stage2024, 3.6
#
#                  jemalloc       no jemalloc
#        JURECA       1               3
#        hambach      2               4
#
python jemalloc_loader_example.py --path aa25f6f4-0f6d-466b-97ea-cb9a985f61f0
python jemalloc_loader_example.py --path 80c532af-433b-4bd1-b09b-9a314cce0910
python jemalloc_loader_example.py --path 3d37f2dd-e667-4921-bdfb-53e9c1851cfe
python jemalloc_loader_example.py --path 26cbade3-b4ca-4f6a-8cc0-3905a3132d20





# slide 9: original finding, stage2025, 3.9
#
#                  jemalloc       no jemalloc
#        JURECA       1               3
#        hambach      2               4
#
python jemalloc_loader_example.py --path d1a382d3-ba1d-4028-b902-03c4f4f285bc
python jemalloc_loader_example.py --path 51463689-0ee3-48d1-bd1f-d46650fd04ed
python jemalloc_loader_example.py --path 297ae1e1-c893-40d1-b30a-4e2dbafcb447
python jemalloc_loader_example.py --path c1388a3f-7e22-4c39-96e3-77eb27d1806c




# slide 10: 8 NUMA domain, NUMA balancing: JURECA on hambach off, stage2025, 3.9
#
#                  jemalloc       no jemalloc
#        JURECA       1               3
#        hambach      2               4
#
python jemalloc_loader_example.py --path d1a382d3-ba1d-4028-b902-03c4f4f285bc
python jemalloc_loader_example.py --path 8ece3da5-59ad-4bd9-9c96-6eba0bf458d6
python jemalloc_loader_example.py --path 297ae1e1-c893-40d1-b30a-4e2dbafcb447
python jemalloc_loader_example.py --path 70acde9a-82da-4830-9365-44043db70aaa



# slide 11: 8 NUMA domain, NUMA balancing on, stage2025, 3.9
#
#                  jemalloc       no jemalloc
#        JURECA       1               3
#        hambach      2               4
#
python jemalloc_loader_example.py --path d1a382d3-ba1d-4028-b902-03c4f4f285bc
python jemalloc_loader_example.py --path d4e585e3-cc1a-48b2-87a5-cfb8dddae683
python jemalloc_loader_example.py --path 297ae1e1-c893-40d1-b30a-4e2dbafcb447
python jemalloc_loader_example.py --path 09f3a966-b441-492a-b8f1-038238d6f690


# slide 12: 8 NUMA domain, NUMA balancing off, stage2025, 3.9
#
#                  jemalloc       no jemalloc
#        JURECA       1               3
#        hambach      2               4
#
python jemalloc_loader_example.py --path b6e0376e-1f24-41d0-91de-245c767364d1
python jemalloc_loader_example.py --path 8ece3da5-59ad-4bd9-9c96-6eba0bf458d6
python jemalloc_loader_example.py --path 5abe747b-8aff-486e-8184-91a26eb10df1
python jemalloc_loader_example.py --path 70acde9a-82da-4830-9365-44043db70aaa


# slide 13: 2 NUMA domain, NUMA balancing on, stage2025, 3.9
#
#                  jemalloc       no jemalloc
#        JURECA       1               3
#        hambach      2               4
#
python jemalloc_loader_example.py --path f6b244f5-0a0f-4189-9625-d22026d1951a
python jemalloc_loader_example.py --path a9be7477-0ab4-4b42-aafa-c654c9618f06
python jemalloc_loader_example.py --path 7f437472-de78-4e26-b1f4-44288be79688
python jemalloc_loader_example.py --path 1f690445-debf-4c11-9cb2-49a31bcbacf6


# slide 14: 2 NUMA domain, NUMA balancing off, stage2025, 3.9
#
#                  jemalloc       no jemalloc
#        JURECA       1               3
#        hambach      2               4
#
python jemalloc_loader_example.py --path 5f84680d-de8c-4e42-a01f-73458c171fae
python jemalloc_loader_example.py --path 51463689-0ee3-48d1-bd1f-d46650fd04ed
python jemalloc_loader_example.py --path e3913ed8-1b89-4368-b977-f7f8400e47d5
python jemalloc_loader_example.py --path c1388a3f-7e22-4c39-96e3-77eb27d1806c


# slide 22: original finding, stage2025, 3.9, where page faults not available in first data
#
#                  jemalloc       no jemalloc
#        JURECA       1               X
#        hambach      2               3
#
python jemalloc_loader_example.py --path 6219e7a5-b6ef-43f4-a78f-3025e68ab290
python jemalloc_loader_example.py --path e7cd87a9-7de5-47b9-8a87-bdfd53eb1a61
python jemalloc_loader_example.py --path c738f00a-cd8f-4293-9fdc-649d780008ea
